### ISSUE TITLE
Large plan content fails to be stored without obvious error

### ISSUE THREAD

**Issue by danwakefield** [dalibo/explain.dalibo.com#6]
When submitting planContent above the limit for LocalStorage (5 mb) it fails without any indication to the user.

E.g https://gist.github.com/steelbrain/e57e508278a79ea4397efba9872b2b17

An error is raised in the console
<img width="846" alt="Screenshot 2022-04-30 at 15 37 20" src="https://user-images.githubusercontent.com/667610/166110024-fdd06223-3e87-4700-a499-4f47f164d5d8.png">

It would be nice to catch the error and tell users that minimizing JSON input would help. 

https://github.com/dalibo/explain.dalibo.com/blob/2f3c61adee821c2bdcdffbf6e5730df382fca5b4/app/static/js/index.js#L59

**Comment by pgiraud** [comment]
Thanks for the report.
Related to https://github.com/dalibo/pev2/issues/481

**Comment by pgiraud** [comment]
Today, we deployed a new version. The plan are now automatically sent to server. The issue with the local storage being full should not happen anymore. Closing.
